# Generated by Django 3.2.8 on 2021-10-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_joboffer_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='availabe',
            new_name='available',
        ),
    ]
